<#
.SYNOPSIS
    Build one of the packaging/sdk packages locally and show what lands inside
    the .nupkg, without Artifactory and without publishing anything.

.DESCRIPTION
    The real package build only happens inside the autogenerated TeamCity job,
    which means a mistake in models.json, the nuspec template or the packed
    layout normally surfaces after a repo has been created and a branch pushed.
    This reproduces that job locally instead.

    It recreates the checkout shape TeamCity produces -- <root>\<name>\ beside
    <root>\common\, because build.cmd reaches for ..\common\nuget\publish.cmd --
    stands in for download.ps1 by copying the payload from this HAL tree, then
    runs the real build-nuget.ps1 and lists the package contents.

    By default the payload is copied out of this tree, so the rehearsal works
    without a credential. Pass -RealDownload to run the actual download.ps1
    instead: that fetches from the pinned Hugging Face revision, verifies against
    the committed SHA256SUMS, and then checks the result is byte-identical to the
    local payload the WER baselines were measured on. It needs HF_TOKEN.

.PARAMETER CommonRepo
    Checkout of git.int.avast.com/sdk/common, which provides create_nuget.ps1
    and bin\nuget.exe.

.EXAMPLE
    git clone https://git.int.avast.com/sdk/common.git C:\Sources\tools\sdk-common
    .\tools\publish\rehearse-sdk-package.ps1 -Package whisper-accuracy-samples
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet(
        "fakeaudio-samples",
        "whisper-accuracy-samples",
        "whisper-multilingual-accuracy-samples",
        "whisper-tiny-multilingual-static"
    )]
    [string]$Package,
    [string]$HalRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path,
    [string]$CommonRepo = "C:\Sources\tools\sdk-common",
    [string]$Root = (Join-Path $env:TEMP "sdk-rehearsal"),
    [string]$Version = "1.0.0",
    [switch]$RealDownload
)

$ErrorActionPreference = "Stop"
chcp 65001 > $null
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
$OutputEncoding = [System.Text.UTF8Encoding]::new()

if (-not (Test-Path -LiteralPath (Join-Path $CommonRepo "nuget\create_nuget.ps1")))
{
    throw ("sdk/common not found at $CommonRepo. Clone " +
        "https://git.int.avast.com/sdk/common.git or pass -CommonRepo.")
}

# models.json key + URL extension, matching download.ps1 (e.g. real_1 + .wav).
function Get-FlatOutputName($property)
{
    $url = [string]$property.Value
    return "$($property.Name)$($url.Substring($url.LastIndexOf('.')))"
}

# Resolve one pinned HF URL back to its local source byte using asset-map.json.
# This also handles renamed nested files: FakeAudio packages
# test_audio/real/1.wav as models/real_1.wav.
function Get-LocalFileFor([string]$url, [string]$halRoot)
{
    if ($url -notmatch '/resolve/[0-9a-f]+/(.+)$')
    {
        throw ("cannot read a Hugging Face path out of '$url'. If these packages " +
            "move to another host, teach this function the new URL shape.")
    }
    $hfPath = $Matches[1]

    $map = (Get-Content -LiteralPath (Join-Path $halRoot "tools\fetch\asset-map.json") -Raw -Encoding UTF8 |
        ConvertFrom-Json).map
    $entry = $map |
        Where-Object { $hfPath -eq $_.hf -or $hfPath.StartsWith("$($_.hf)/") } |
        Sort-Object { $_.hf.Length } -Descending |
        Select-Object -First 1
    if (-not $entry)
    {
        throw "no asset-map.json entry maps the Hugging Face path '$hfPath' back to a local directory"
    }

    $suffix = $hfPath.Substring($entry.hf.Length).TrimStart("/")
    return Join-Path (Join-Path $halRoot $entry.local) ($suffix -replace '/', '\')
}

$work = Join-Path $Root $Package
Remove-Item -Recurse -Force $work -ErrorAction Ignore
New-Item -ItemType Directory -Force $work | Out-Null
Copy-Item (Join-Path $HalRoot "packaging\sdk\$Package\*") $work -Recurse -Force
Remove-Item -Recurse -Force (Join-Path $work "models") -ErrorAction Ignore
Remove-Item -Recurse -Force (Join-Path $work "nugets") -ErrorAction Ignore

$commonLink = Join-Path $Root "common"
if (-not (Test-Path -LiteralPath $commonLink))
{
    New-Item -ItemType Junction -Path $commonLink -Target $CommonRepo | Out-Null
}

$models = Join-Path $work "models"
New-Item -ItemType Directory -Force $models | Out-Null
$entries = @((Get-Content (Join-Path $work "models.json") -Raw | ConvertFrom-Json).PSObject.Properties)
if (-not $entries)
{
    throw ("models.json in packaging\sdk\$Package is empty. Run " +
        "write-hf-manifests.ps1 to generate it.")
}

if ($RealDownload)
{
    # Run the actual download.ps1 under Windows PowerShell, because that is what
    # build.cmd invokes on the agent and it is not the same interpreter as the one
    # running this script. Its checksum verification against SHA256SUMS is the
    # part worth exercising: it proves the URLs, the credential handling and the
    # committed hashes all agree.
    Write-Host "running the real download.ps1 (Windows PowerShell, as build.cmd does)" -ForegroundColor Cyan
    Push-Location $work
    try
    {
        & powershell -NoProfile -File .\download.ps1 2>&1 | ForEach-Object { "  $_" }
        if ($LASTEXITCODE -ne 0) { throw "download.ps1 exited $LASTEXITCODE" }
    }
    finally
    {
        Pop-Location
    }

    # Downloading is not the same as downloading the right thing. Compare what
    # landed against this tree, which is what the baselines were measured on.
    $drift = @()
    foreach ($property in $entries)
    {
        $name = Get-FlatOutputName $property
        $got = Join-Path $models $name
        $want = Get-LocalFileFor ([string]$property.Value) $HalRoot
        if (-not (Test-Path -LiteralPath $got)) { $drift += "$name : not downloaded"; continue }
        if (-not (Test-Path -LiteralPath $want)) { continue }
        $a = (Get-FileHash -LiteralPath $got -Algorithm SHA256).Hash
        $b = (Get-FileHash -LiteralPath $want -Algorithm SHA256).Hash
        if ($a -ne $b) { $drift += "$name : differs from the local payload" }
    }
    if ($drift) { throw ("downloaded payload does not match this tree:`n  " + ($drift -join "`n  ")) }
    Write-Host ("downloaded {0} file(s), all identical to their mapped local payloads" -f $entries.Count) -ForegroundColor Green
}
else
{
    foreach ($property in $entries)
    {
        $name = Get-FlatOutputName $property
        $source = Get-LocalFileFor ([string]$property.Value) $HalRoot
        if (-not (Test-Path -LiteralPath $source))
        {
            throw "models.json names $name, which is not at $source"
        }
        Copy-Item -LiteralPath $source -Destination (Join-Path $models $name) -Force
    }
    Write-Host ("staged {0} file(s) into models\ (copied locally; pass -RealDownload to fetch)" -f $entries.Count)
}

$contract = Join-Path $work "samples.json"
if ((Test-Path -LiteralPath $contract) -and
    -not (Test-Path -LiteralPath (Join-Path $models "samples.json")))
{
    Copy-Item -LiteralPath $contract -Destination (Join-Path $models "samples.json")
}

Push-Location $work
try
{
    & powershell -NoProfile -File .\build-nuget.ps1 $Version 2>&1 |
        Where-Object { $_ -notmatch '^\s*$' } | ForEach-Object { "  $_" }
    if ($LASTEXITCODE -ne 0) { throw "build-nuget.ps1 exited $LASTEXITCODE" }
}
finally
{
    Pop-Location
}

$nupkg = Get-ChildItem (Join-Path $work "nugets\*.nupkg") -ErrorAction Stop
Write-Host ""
Write-Host ("PACKAGE {0} ({1:N2} MB)" -f $nupkg.Name, ($nupkg.Length / 1MB)) -ForegroundColor Green

Add-Type -AssemblyName System.IO.Compression.FileSystem
$zip = [IO.Compression.ZipFile]::OpenRead($nupkg.FullName)
try
{
    $zip.Entries | Sort-Object FullName | ForEach-Object {
        if ($_.FullName -notmatch '^(\[Content_Types\]|_rels/|package/)')
        {
            '  {0,12:N0}  {1}' -f $_.Length, $_.FullName
        }
    }
    $nuspec = $zip.Entries |
        Where-Object { $_.FullName -match '\.nuspec$' -and $_.FullName -notmatch '/' }
    if ($nuspec)
    {
        Write-Host ""
        Write-Host "  --- rendered nuspec ---"
        $reader = New-Object IO.StreamReader($nuspec.Open())
        $reader.ReadToEnd() -split "`n" |
            Where-Object { $_ -match 'id>|version>|title>|description>' } |
            ForEach-Object { "  $($_.Trim())" }
        $reader.Dispose()
    }
}
finally
{
    $zip.Dispose()
}
